### ISSUE TITLE
System.DllNotFoundException: 'Unable to load DLL 'libspreads_lmdb': The specified module could not be found. (Exception from HRESULT: 0x8007007E)'

### ISSUE THREAD

**Issue by master117** [Nekromancer/SoundFingerprinting.Extensions.LMDB#1]
I get the error from the title when running:

`var modelService = new LMDBModelService("db")`

https://i.imgur.com/R7tR8pS.png

**Comment by jakoss** [comment]
Hi,

Thanks for taking interest in library. Spreads.LMDB library, which is .NET wrapper over native LMDB binary, made a change that requires you to provide proper native binary yourself from here: https://github.com/Spreads/Spreads.LMDB/tree/master/lib/runtimes. See related thread on library github: https://github.com/Spreads/Spreads.LMDB/issues/28

In my project i just attached this binary to project files with "Copy on Build" property - works just fine.

**Comment by master117** [comment]
Thanks, that solution worked right away. Sadly I got stuck on a second error right away.

https://i.imgur.com/qpTums6.png

`public static void FindMatch(IModelService modelService)
        {
            int secondsToAnalyze = 5; // number of seconds to analyze from query file
            int startAtSecond = 0; // start at the begining
            
            // query the underlying database for similar audio sub-fingerprints
            var queryResult = QueryCommandBuilder.Instance.BuildQueryCommand()
                .From(OutputFilePath, secondsToAnalyze, startAtSecond)
                .UsingServices(modelService, audioService)
                .Query().Result;

            if (queryResult.BestMatch != null)
            {
                var metadata = Regex.Split(queryResult.BestMatch.Track.Title, @" - ");
                var answer = metadata[0];
                Thread newThread = new Thread(new ParameterizedThreadStart(ThreadMethod));
                newThread.SetApartmentState(ApartmentState.STA);
                newThread.Start(answer);

                Log.WriteLine(queryResult.BestMatch.Track.Title);
            }
            else
                Log.WriteLine("Not found");
        }`

Note that I'm trying to run synchronously, as I'm using just single samples from realtime data, tho I assume that is not related to the problem. Or would you prefer me to open a new Issue for this?

**Comment by jakoss** [comment]
What are you providing as `LMDBModelService` constructor parameter? Seems like lmdb database wasn't opened. Note that this constructor parameter has to be directory, not a file (you just point to db directory you want to have and lmdb will create it's files for itself. 
Make sure you are using native library that match to your compilation target. If you are using "AnyCPU" i would strongly advice to use x64 or x32 explicitly.
If none of this will help you - please provide sample that i can reproduce locally

**Comment by master117** [comment]
I'm running x64 https://i.imgur.com/6DCbwCG.png
I'm pointing at a folder that has both db files in it: https://i.imgur.com/hTTK5LV.png
`Console.WriteLine("Loaded " + modelService.ReadAllTracks().Count() + " tracks");`
prints: Loaded 2836 tracks

Here is a not working sample.

    class Program
    {
        private static readonly NAudioService audioService = new NAudioService(); // default audio library
        private static readonly string OutputFolder = "Temp";
        private static readonly string OutputFilePath = Path.Combine(OutputFolder, "recorded.wav");
        private static readonly string SnapShotPath = @"E:\FingerPrintDB.ss";
        private static readonly string LMDBPath = @"E:\FingerPrintDB";
        static void Main(string[] args)
        {
            Directory.CreateDirectory(OutputFolder);

            Console.WriteLine("Loading Library");
            using (var modelService = new LMDBModelService(LMDBPath)) 
            {
                LoadAudioLibrary(modelService);
                Console.WriteLine("Loaded " + modelService.ReadAllTracks().Count() + " tracks");
                StartDetection(modelService);
            }
        }

        //Loads AudioLibrary from filesystem if possible, otherwise creates it on the spot
        public static void LoadAudioLibrary(IModelService modelService)
        {
            //LMDB Version
            Console.WriteLine("Adding new Entries to Library");
            CreateAudioLibrary(modelService);
        }

        //Build Fingerprint Library from local data
        public static void CreateAudioLibrary(IModelService modelService)
        {
            //Get all .mp3s as paths
            var files = Directory.GetFiles(@"E:\OPEDMP3", "*.mp3");
            int counter = 0;

            foreach (var file in files)
            {
                try
                {
                    //Remove '.mp3' -> title, aquire metadata
                    var title = Path.GetFileNameWithoutExtension(file);

                    //only work files that are new
                    if (!modelService.ReadTrackByTitle(title).Any())
                    {
                        Console.WriteLine("Working on: " + title + " " + counter + "/" + files.Length);
                        var metadata = Regex.Split(title, @" - ");
                        TimeSpan duration;

                        using (var reader = new Mp3FileReader(file))
                            duration = reader.TotalTime;

                        //Hash and Store
                        StoreFingerPrint(modelService, file, title, "", duration.TotalSeconds);
                    }
                }
                catch (Exception e)
                {
                    Console.WriteLine(file);
                    Console.WriteLine(e.ToString());
                }

                counter++;
            }
        }

        //Create and store a single fingerprint
        public static void StoreFingerPrint(IModelService modelService, string pathToAudioFile, string title, string artist, double duration)
        {
            var track = new TrackInfo(pathToAudioFile, title, artist, duration);

            // create fingerprints
            var hashedFingerprints = FingerprintCommandBuilder.Instance
                .BuildFingerprintCommand()
                .From(pathToAudioFile)
                .UsingServices(audioService)
                .Hash().Result;

            // store hashes in the database for later retrieval
            modelService.Insert(track, hashedFingerprints);
        }

        //Waits until a user presses a button and then grabs x seconds of current playback
        public static void StartDetection(IModelService modelService)
        {
            //Delete old output file
            if (File.Exists(OutputFilePath))
                File.Delete(OutputFilePath);

            //Ask for start, then "Listen"
            Console.WriteLine("Press any key to start recording");
            Console.ReadKey();
            //Used to show progress
            DateTime lastDot = DateTime.Now;
            Console.Write("Listening");

            //Capture audio from audiodevice
            var capture = new WasapiLoopbackCapture();
            var writer = new WaveFileWriter(OutputFilePath, capture.WaveFormat);

            capture.DataAvailable += (s, a) =>
            {
                //Update Progress
                if (DateTime.Now > lastDot.AddSeconds(1))
                {
                    Console.Write(".");
                    lastDot = DateTime.Now;
                }

                //Write audio from stream to file until we reached the desired time
                writer.Write(a.Buffer, 0, a.BytesRecorded);
                if (writer.Position > capture.WaveFormat.AverageBytesPerSecond * 5)
                {
                    capture.StopRecording();
                }
            };

            //Stop recording and start the matchfinding process
            capture.RecordingStopped += (s, a) =>
            {
                writer.Dispose();
                writer = null;
                capture.Dispose();

                FindMatch(modelService);
            };

            capture.StartRecording();
        }

        //Finds a match for a given recording
        public static void FindMatch(IModelService modelService)
        {
            //clearing log
            Console.WriteLine("");

            int secondsToAnalyze = 5; // number of seconds to analyze from query file
            int startAtSecond = 0; // start at the begining
            
            // query the underlying database for similar audio sub-fingerprints
            var queryResult = QueryCommandBuilder.Instance.BuildQueryCommand()
                .From(OutputFilePath, secondsToAnalyze, startAtSecond)
                .UsingServices(modelService, audioService)
                .Query().Result;

            if (queryResult.BestMatch != null)
            {
                var metadata = Regex.Split(queryResult.BestMatch.Track.Title, @" - ");
                var answer = metadata[0];
                Console.WriteLine(queryResult.BestMatch.Track.Title);
            }
            else
            {
                Console.WriteLine("Not found");
            }

            StartDetection(modelService);
        }
    }
```

**Comment by jakoss** [comment]
Ok, i think i see what is an issue here. `StartDetection` function is starting asynchronous recording and then ends. `FindMatch` is called from event `RecordingStopped`. But you already disposed `modelService` because function `StartDetection` ended. You have to change dispose logic. Look at `StartRecording` code. It just creates thread and exits https://github.com/naudio/NAudio/blob/master/NAudio/Wave/WaveInputs/WasapiCapture.cs#L186

**Comment by jakoss** [comment]
To make it work the simplest way - just add `Console.ReadKey();` after `capture.StartRecording();`

**Comment by master117** [comment]
Ah, of course, thank you very much. I would have expected a different error coming from an early dispose.

LMDB loads a lot faster than InMemory while detecting at nearly the same speed for me, so, thank you very much for creating this.

**Comment by jakoss** [comment]
No problem. LMDB doesn't have to load anything to memory at start, so startup time is much better. It gets slower when you're using over 50k tracks in database, but still acceptable :)
