### ISSUE TITLE
When can you update to the latest version?

### ISSUE THREAD

**Issue by naren-96** [Nekromancer/SoundFingerprinting.Extensions.LMDB#4]
When can you update to the latest version? For new version SoundFingerprinting

**Comment by jakoss** [comment]
Done. Keep in mind that i don't have production data to confirm that it's working properly. It should, tests are mirrored from `SoundFingerprinting`, but i don't have any data set to test it on bigger database

**Comment by Hamsterland** [comment]
@jakoss 
```cs
modelService.Insert(TrackInfo trackInfo, Hashes hashes);
```
But the `Hash` method returns an `AVHashes`
```cs
var fingerprints = await FingerprintCommandBuilder.Instance
    .BuildFingerprintCommand()
    .From(path)
    .Hash();

// fingerprints is AVHashes
```
